include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [build/**]
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    camel_case_types: true
    todo: false
    omit_local_variable_types: false