name: mongol
description: Flutter widget package for displaying and editing vertical Mongolian text.
version: 3.0.0
homepage: https://github.com/suragch/mongol

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  characters: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  path: any
  fake_async: any
  clock: any
  stack_trace: any
  test_api: any
  meta: any
